# baseURL: "https://tomas2p.github.io/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: Tomas2p
paginate: 5
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
  disableXML: true
  # minifyOutput: true

params:
  env: production
  author: Tomás Pino Pérez
  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false

  assets:
    favicon: "/favicon_io/favicon.ico"

  profileMode:
    enabled: true
    title: Tomás Pino Pérez
    subtitle:
      "Ingeniero en formación, apasionado por la programación y la narrativa visual.
      Equilibrando líneas de código con guiones de cortometrajes. 💻🎞️"
    imageUrl: "https://avatars.githubusercontent.com/u/91573621?v=4" # optional
    imageTitle: "<title of image as alt>" # optional
    # imageWidth: 200 # custom size
    # imageHeight: 200 # custom size
    buttons:
      - name: Proyectos
        url: /proyects

  #   homeInfoParams:
  #     Title: Portfolio
  #     Content: "Ingeniero en formación, apasionado por la programación y la narrativa visual.
  #     Equilibrando líneas de código con guiones de cortometrajes. 💻🎞️"
  #
  #   mainSections:
  #     - proyects
  #     - blog

  socialIcons:
    - name: Instagram
      url: "https://instagram.com/tomas2p11"
    - name: Youtube
      url: "https://www.youtube.com/@tomas2p11"
    - name: Github
      url: "https://github.com/tomas2p"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - identifier: proyectos
      name: Proyectos
      url: /proyects
      weight: 1
    # - identifier: archive
    #   name: Archivo
    #   url: /archive
    #   weight: 15
    # - identifier: artículos
    #   name: Blog
    #   url: /blog
    #   weight: 2
    - identifier: etiquetas
      name: Etiquetas
      url: /tags
      weight: 3
    # - identifier: buscar
    #   name: Buscar
    #   url: /search
    #   weight: 4
