baseURL: "https://tomas2p.github.io/"
title: Tomas2p
paginate: 5
theme: PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  # env: production
  author: Tomas2p
  description: "Portfolio de Tomas2p"
  # mainSections: proyects
  favicon: /logo/1f3b4.ico
  DateFormat: "2006-01-02"
  useCustomAnalytics: false
  disableAnchoredHeadings: true
  disableScrollToTop: false
  logo:
    text: "Tomas2p"
    # La siguiente linea esta rara no sirve, hay que cambiar icon en la línea 94 de themes/PaperModX/layouts/partials/header.html
    icon: "https://images.emojiterra.com/google/android-11/512px/1f3b4.png"

  # Theme Params
  defaultTheme: auto
  # disableThemeToggle: true
  DisableLanguageSwitch: true
  # disableSpecial1stPost: true
  TocOpen: true
  TocSide: right
  EnableInstantClick: true
  EnableImageZoom: true
  ShowShareButtons: true
  ShowAuthor: true
  ShowDraft: true
  ShowWordCount: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: false
  ShowRssButtonInSectionTermList: false
  comments: false

  socialIcons:
    - name: instagram
      url: "https://instagram.com/tomas2p11"
    - name: youtube-simple
      url: "https://www.youtube.com/@tomas2p11"
    - name: github-simple
      url: "https://github.com/tomas2p"

  profileMode:
    enabled: true
    title: Tomás Pino Pérez
    subtitle: >
      Ingeniero en formación, apasionado por la programación y la narrativa visual.
      Equilibrando líneas de código con guiones de cortometrajes. 💻🎞️
    imageUrl: "https://avatars.githubusercontent.com/u/91573621?v=4" # optional
    imageTitle: "Imagen de perfil de Toms2p" # optional
    # imageWidth: 200 # custom size
    # imageHeight: 200 # custom size
    buttons:
      - name: Proyectos
        url: /proyects

menu:
  main:
    - identifier: proyects
      name: Proyectos
      url: /proyects
      weight: 1
    - identifier: tags
      name: Etiquetas
      url: /tags
      weight: 2

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
